### ISSUE TITLE
Getting Cant play video

### ISSUE THREAD

**Issue by wajdan846** [chandilsachin/VideoDownloadAndPlay#5]
Hi ,
Iv added your source in my android app but im facing the specified issue while running the code below.I have also attached the logs
**CODE**

```
    private void startServer()
    {
        String mediaURL ="rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov";
        String pathToVideo = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).getPath();
        Log.d("wajdan",pathToVideo);

        videoService = VideoDownloadAndPlayService.startServer(this, mediaURL,pathToVideo, "127.0.0.1", new VideoDownloadAndPlayService.VideoStreamInterface()
        {
            @Override
            public void onServerStart(String videoStreamUrl)
            {
                Log.d("wajdan",videoStreamUrl);
                // use videoStreamUrl to play video through media player
                VideoView videoView = (VideoView) findViewById(R.id.videoview);
                MediaController mediaController = new MediaController(mContext);
                mediaController.setAnchorView(videoView);
                mediaController.setMediaPlayer(videoView);
                Uri video = Uri.parse(videoStreamUrl);
                videoView.setMediaController(mediaController);
                videoView.setVideoURI(video);
                videoView.start();
            }
        });

    }`

```
**LOGS**

`05-16 16:04:50.354 1745-2243/org.app.pk.anzen E/com.sachinchandil.videodownloadandplay.LocalFileStreamingServer: Server started at http://127.0.0.1:47807
05-16 16:04:50.434 1745-2252/org.app.pk.anzen E/com.sachinchandil.videodownloadandplay.LocalFileStreamingServer: running
05-16 16:04:50.774 1745-2252/org.app.pk.anzen E/com.sachinchandil.videodownloadandplay.LocalFileStreamingServer: client connected at 47807
05-16 16:04:50.784 1745-2252/org.app.pk.anzen E/com.sachinchandil.videodownloadandplay.LocalFileStreamingServer: respurcePath is: /storage/emulated/0/Download
05-16 16:04:50.784 1745-2252/org.app.pk.anzen E/com.sachinchandil.videodownloadandplay.LocalFileStreamingServer: processing request...
05-16 16:04:50.784 1745-2252/org.app.pk.anzen E/com.sachinchandil.videodownloadandplay.LocalFileStreamingServer: Header: user-agent : stagefright/1.2 (Linux;Android 5.0.2)
05-16 16:04:50.784 1745-2252/org.app.pk.anzen E/com.sachinchandil.videodownloadandplay.LocalFileStreamingServer: Header: accept-encoding : gzip
05-16 16:04:50.784 1745-2252/org.app.pk.anzen E/com.sachinchandil.videodownloadandplay.LocalFileStreamingServer: Header: host : 127.0.0.1:47807
05-16 16:04:50.784 1745-2252/org.app.pk.anzen E/com.sachinchandil.videodownloadandplay.LocalFileStreamingServer: Header: connection : Keep-Alive
05-16 16:04:50.784 1745-2252/org.app.pk.anzen W/System.err:     at com.sachinchandil.videodownloadandplay.LocalFileStreamingServer$ExternalResourceDataSource.getInputStream(LocalFileStreamingServer.java:563)
05-16 16:04:50.784 1745-2252/org.app.pk.anzen W/System.err:     at com.sachinchandil.videodownloadandplay.LocalFileStreamingServer$ExternalResourceDataSource.createInputStream(LocalFileStreamingServer.java:536)
05-16 16:04:50.784 1745-2252/org.app.pk.anzen W/System.err:     at com.sachinchandil.videodownloadandplay.LocalFileStreamingServer.processRequest(LocalFileStreamingServer.java:275)
05-16 16:04:50.784 1745-2252/org.app.pk.anzen W/System.err:     at com.sachinchandil.videodownloadandplay.LocalFileStreamingServer.run(LocalFileStreamingServer.java:153)
05-16 16:04:50.784 1745-2252/org.app.pk.anzen E/com.sachinchandil.videodownloadandplay.LocalFileStreamingServer: file exists??true and content length is: 4096
05-16 16:04:50.784 1745-2252/org.app.pk.anzen E/com.sachinchandil.videodownloadandplay.LocalFileStreamingServer: writing to client
05-16 16:04:50.784 1745-2252/org.app.pk.anzen E/com.sachinchandil.videodownloadandplay.LocalFileStreamingServer: Error streaming file content.
                                                                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'long java.io.InputStream.skip(long)' on a null object reference
                                                                                                                     at com.sachinchandil.videodownloadandplay.LocalFileStreamingServer.processRequest(LocalFileStreamingServer.java:283)
                                                                                                                     at com.sachinchandil.videodownloadandplay.LocalFileStreamingServer.run(LocalFileStreamingServer.java:153)
                                                                                                                     at java.lang.Thread.run(Thread.java:818)
05-16 16:05:00.784 1745-2252/org.app.pk.anzen E/com.sachinchandil.videodownloadandplay.LocalFileStreamingServer: No client connected, waiting for client...
                                                                                                                 java.net.SocketTimeoutException
                                                                                                                     at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:99)
                                                                                                                     at java.net.ServerSocket.implAccept(ServerSocket.java:216)
                                                                                                                     at java.net.ServerSocket.accept(ServerSocket.java:140)
                                                                                                                     at com.sachinchandil.videodownloadandplay.LocalFileStreamingServer.run(LocalFileStreamingServer.java:144)
                                                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                                                  Caused by: android.system.ErrnoException: accept failed: EAGAIN (Try again)
                                                                                                                     at libcore.io.Posix.accept(Native Method)
                                                                                                                     at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
                                                                                                                     at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
                                                                                                                     at java.net.ServerSocket.implAccept(ServerSocket.java:216) 
                                                                                                                     at java.net.ServerSocket.accept(ServerSocket.java:140) 
                                                                                                                     at com.sachinchandil.videodownloadandplay.LocalFileStreamingServer.run(LocalFileStreamingServer.java:144) 
                                                                                                                     at java.lang.Thread.run(Thread.java:818) 
05-16 16:05:10.784 1745-2252/org.app.pk.anzen E/com.sachinchandil.videodownloadandplay.LocalFileStreamingServer: No client connected, waiting for client...
         `

**Comment by EduApps-CDG** [comment]
Same here
